### ISSUE TITLE
What parameters is really trained during P-tuning v2?

### ISSUE THREAD

**Issue by petrovlesha** [THUDM/P-tuning-v2#1]
Hello!

Thanks a lot for a such well-written article! It's so impressive improvement of P-tuning.

Could you please clarify what parameters are really tuned during p-tuning?  Is it MLP producing input embeddings for a large model? Or maybe it's copy of some layers e.g. key-value projection for tuned prefix tokens?

**Comment by Xiao9905** [comment]
Yes, your understanding is correct.

**Comment by petrovlesha** [comment]
Thank you! That helped a lot.
