### ISSUE TITLE
What do you mean by ascending and descending order?

### ISSUE THREAD

**Issue by PrettyMeng** [THUDM/P-tuning-v2#10]
Hi there,

Thanks for your great work! In section 4.4, you did an ablation study about adding prompt to transformer layers in **descending order** or **ascending order**. I don't quite understand this difference. Could you please elaborate on this?

**Comment by Xiao9905** [comment]
Hi,
In the ablation study, we first control the number of transformer layers to add prompts (e.g., k layers). When added in descending order, it means these 4 layers are the **last-k layers** (e.g., layer 21-24 for BERT-large when k=4) of the transformer. If added in ascending order, it means these 4 layers are the **top-k layers** (e.g., layer 1-4 for BERT-large when k=4).
