### ISSUE TITLE
past_key_values=past_key_values

### ISSUE THREAD

**Issue by Coding-Zuo** [THUDM/P-tuning-v2#14]
Hi, I found in the official huggingface documentation that this “past_key_values=past_key_values” parameter is only useful for accelerating precompute. Can you please explain which is p-tuning v2, prefix or prompt?

Why do I think Deep Prompt Tuning is --prompt instead of --prefix?

Thank you for your code contributions.

**Comment by Xiao9905** [comment]
Hi,
You need to understand how `past_key_values` really functions in the attention computation, which is an implementation trick we inherit from prefix tuning. `--prefix` does refer to deep prompt tuning, and `--prompt` refer to prompt tuning.
