### ISSUE TITLE
sequence_classification.py

### ISSUE THREAD

**Issue by zhaogangthu** [THUDM/P-tuning-v2#18]
`## pooled_output = outputs[1]
sequence_output = outputs[0]
sequence_output = sequence_output[:, self.pre_seq_len:, :].contiguous()
first_token_tensor = sequence_output[:, 0]
pooled_output = self.bert.pooler.dense(first_token_tensor)
pooled_output = self.bert.pooler.activation(pooled_output)`
请问作者做这段修改的目的是什么呢，原方法经过测试效果还是不错的。

**Comment by DaoD** [comment]
这是为了拿CLS位置对应的向量。如果直接取outputs[1]拿的是prompt里面第一个词的向量

**Comment by Xiao9905** [comment]
是的，理论上在P-tuning v1里，你拿prompt里第一个词的向量和[CLS]的向量做其实区别不会大，因为都是special token。不过为了方法实现的严谨性，我们修改成了用[CLS]向量。

**Comment by zhaogangthu** [comment]
`        outputs = self.bert(
            input_ids,
            attention_mask=attention_mask,
            token_type_ids=token_type_ids,
            position_ids=position_ids,
            head_mask=head_mask,
            inputs_embeds=inputs_embeds,
            output_attentions=output_attentions,
            output_hidden_states=output_hidden_states,
            return_dict=return_dict,
            past_key_values=past_key_values,
        )
`
past_key_values这个参数会改变cls位置吗？实际上input_ids前面并没有拼接prompt，我理解outputs取出的第一个位置还是cls。举个例子，如果输入是128维，past_key_values 4维，则qkv分别为128，134，134维度，q*k=128*134，q*k*v又回到了128维，所以我理解output输出还是128维，第一个位置还是第一个字的位置吧，只是信息包含了past_key_values的信息。

**Comment by Xiao9905** [comment]
@zhaogangthu 你好，我们这部分修改的代码（见[pull request 16](https://github.com/THUDM/P-tuning-v2/pull/16)）所位于的类为`BertPromptForSequenceClassification`，指的是对P-tuning v1的实现。请注意与`BertPrefixForSequenceClassification`（即对P-tuning v2）的实现进行区分。

在`BertPromptForSequenceClassification`中的[Line 278](https://github.com/THUDM/P-tuning-v2/blob/bb07da776e8bbeb1a8c061553a87734e950966d9/model/sequence_classification.py#L278)，你可以看到v1的实现并没有使用past_key_values。我们并未修改v2实现的代码中取出[CLS]的位置。

**Comment by zhaogangthu** [comment]
明白了，谢谢两位，我没有注意到是p-tuning v1的实现，这样看就没有问题了。

**Comment by LeeShiyang** [comment]
Hi 你好，我仔细看了一下代码，如果把prompt 作为 past key value 传入进去，那么bert返回的pooled_output = outputs[1] 对应的是input_ids中第一个词做的linear projection. 我看code的实现第一个词用的是[PAD]，请问为什么不用[CLS] token呢？
