### ISSUE TITLE
dataset ner

### ISSUE THREAD

**Issue by zhishui3** [THUDM/P-tuning-v2#21]
您好，请问ner 数据集的格式是什么样的呀？没下下来
raise FileNotFoundError("Local file {} doesn't exist".format(url_or_filename))
FileNotFoundError: Local file tasks/ner/datasets/../../../data/ontoNotes/train.sd.conllx doesn't exis

NERDataset 这个类里面，也看不太明白数据是什么样的
求解答，谢谢Thanks♪(･ω･)ﾉ您

**Comment by Xiao9905** [comment]
Hi @zhishui3 , 
Have you tried downloading ner datasets? The dataset for sequence tagging is independently provided in `README.md`, rather than from huggingface dataset api.
