### ISSUE TITLE
您好我有个疑问，关于表一的supergule数据集

### ISSUE THREAD

**Issue by sheepi** [THUDM/P-tuning-v2#25]
您好，请问表一基于BERT-large的superglue数据集中PT方法和您之前那篇论文P-tuning方法在superglue的效果差别为什么这么大？是因为冻结参数和没冻结参数的原因嘛？代码中没有找到，不好意思打扰了！

**Comment by Xiao9905** [comment]
@sheepi 

是的，在v1的论文中，我们没有冻结superglue训练时模型参数，而LAMA时是冻结的（均可参考原文说明）；v2的所有PT/PT-2实验都是在冻结模型参数的情况下进行的

**Comment by Xiao9905** [comment]
@sheepi ,

Has your problem got resolved? Please feel free to reopen the issue if necessary.
