### ISSUE TITLE
Question about "deep prompts"

### ISSUE THREAD

**Issue by JetRunner** [THUDM/P-tuning-v2#26]
Hi,

I've seen issues asking about the `past_key_value` implementation and I've tried a code snippet to confirm if it's consistent with what's described in the paper. However, it doesn't seem to work - for different inputs, the first few tokens (i.e., the prompts) are not identical. Could you please take a look at the code snippet to see if it's correct and where the problem is?

```python
    config = RobertaConfig.from_pretrained('roberta-base')
    config.pre_seq_len = 2
    config.prefix_projection = False

    model = RobertaPrefixForSequenceClassification.from_pretrained('roberta-base', config=config)

    tokenizer = AutoTokenizer.from_pretrained('roberta-base')

    sentences = ['This is an example sentence', 'Each sentence is converted']

    encoded_input = tokenizer(sentences, padding=True, truncation=True, return_tensors='pt')

    with torch.no_grad():
        model_output = model(**encoded_input, output_hidden_states=True)
        layer_hidden_states = model_output['hidden_states'][1:]  # discard the output of embedding layer
        for hidden_state in layer_hidden_states:
            deep_prompts = hidden_state[:, :model.pre_seq_len, :]  # [batch_size, seq_len, hidden_size]
            assert deep_prompts[0].equal(deep_prompts[1])
```

**Comment by Xiao9905** [comment]
@JetRunner ,

Hi, if you look into the implementation of `past_key_values` in [huggingface transformers](https://github.com/huggingface/transformers/blob/db7d6a80e82d66127b2a44b6e3382969fdc8b207/src/transformers/models/roberta/modeling_roberta.py#L222), you will notice that it does not put the prefix token embeddings in the output hidden_states.

**Comment by JetRunner** [comment]
@Xiao9905 Thanks for your rapid response! Any idea how to get these prompt vectors?

**Comment by Xiao9905** [comment]
@JetRunner ,

If I understand correctly, you may want the embeddings in `self.prefix_encoder` ([code](https://github.com/THUDM/P-tuning-v2/blob/main/model/prefix_encoder.py))

**Comment by JetRunner** [comment]
> @JetRunner ,
> 
> 
> 
> If I understand correctly, you may want the embeddings in `self.prefix_encoder` ([code](https://github.com/THUDM/P-tuning-v2/blob/main/model/prefix_encoder.py))

Not exactly but thanks anyway!
