### ISSUE TITLE
About the results on the CB dataset

### ISSUE THREAD

**Issue by Dicer-Zz** [THUDM/P-tuning-v2#35]
Why does the effect of fine-tuning on the CB dataset using Bert-large in this paper exceed the SuperGLUE [baseline](https://super.gluebenchmark.com/leaderboard) by more than ten absolute points (83.6 -> 94.6)? And the results on other datasets are not much different.

**Comment by Xiao9905** [comment]
@Dicer-Zz Hi,

We report the results on the development set of [SuperGLUE](https://arxiv.org/pdf/1905.00537.pdf) (Page 16, Table 4).

**Comment by Dicer-Zz** [comment]
Thank you for your quick reply! I get it.
