### ISSUE TITLE
P-tuning v2在少样本上的效果如何呢？

### ISSUE THREAD

**Issue by zdgithub** [THUDM/P-tuning-v2#38]
你好！我发现P-Tuning v2论文中提到所有实验都在**全量数据**上做的，那么在**少样本**设定下的效果如何呢，能赶上fine-tune吗？

**Comment by dyh1998** [comment]
哇哇哇 恨我想法一样  我发邮件给了作者，感谢纪开轩的回答，以下是回复内容，希望能帮助你
![image](https://user-images.githubusercontent.com/63230774/184108404-db9ae5e0-9334-4164-a5e6-fc939b66e1bc.png)

**Comment by Xiao9905** [comment]
@zdgithub Hi,

我们当时没有时间研究其在小样本上的结果。不过后续有工作进行了实验，例如[BBT](https://arxiv.org/pdf/2201.03514.pdf)等很多工作；他们的实验结果可以作一定的参考用。

**Comment by zdgithub** [comment]
感谢回复！
