### ISSUE TITLE
Download Links for Models Appear to be Switched

### ISSUE THREAD

**Issue by ethankim00** [THUDM/P-tuning-v2#39]
Links for the PT-retrieval models in the README table appear to be switched around

**Comment by Xiao9905** [comment]
@ethankim00 Hi，

We check the links and find them to work well. Could you please try again and see if it still breaks down?

**Comment by ethankim00** [comment]
The link in the table under DPR + FT links to a model titled `ptv2.colbert.msmarco.cosine.1e-3.64.zip`. Under COLBERT + DPR the model is `msmarco.psg.l2`. I believe these are switched. I'm interested in finding which is the multidata finetuned DPR model.

**Comment by rainatam** [comment]
@ethankim00 
Thanks for the reminder, I just exchanged the links under DPR+FT and ColBERT+PT. The multidata finetuned DPR model can be obtained from the link of DPR+FT now. Please feel free to have it.

**Comment by ethankim00** [comment]
Thank you!
