### ISSUE TITLE
Can you provide the GPT2 example? 

### ISSUE THREAD

**Issue by PoodleWang** [THUDM/P-tuning-v2#45]
Would you be able to provide the gpt2 example for p-tuning v2?

**Comment by PoodleWang** [comment]
@Xiao9905

**Comment by Xiao9905** [comment]
@PoodleWang Hi,

We do not implement p-tuning v2 for GPT-style models in this work. However, you can refer to [Prefix-Tuning](https://github.com/XiangLi1999/PrefixTuning)'s implementation, which is for GPT models on generation tasks only.
