### ISSUE TITLE
P-tuning v2在NER任务上表现正常，但在分类任务上不收敛

### ISSUE THREAD

**Issue by sxthunder** [THUDM/P-tuning-v2#5]
您好，我们按照文中方法在人民日报NER数据集上进行了复现，所得到结论和文中基本一致；但是我们在RTE和蚂蚁金服文本相似度两个分类数据集上发现并不收敛，我们尝试过MLP和LSTM对prefix embedding进行重参数化但收效甚微。请问作者在做分类相关数据集时是否遇到过此类情况？

以蚂蚁金服数据集为例，模型的loss从一开始就不下降，最终再验证集上会全部预测数量较多的类别。
我们对比过NER和分类的梯度，也没有发现明显区别

模型层面我们尝试过Roberta-large Bert-large 以及Bert-base

**Comment by genggui001** [comment]
我自己实现的在中文CMNLI上也观察到了类似的不收敛现象，求参考大佬代码

**Comment by sxthunder** [comment]
> 我自己实现的在中文CMNLI上也观察到了类似的不收敛现象，求参考大佬代码

你好，请问你尝试过4-12的prompt length和1e-2左右的learning rate吗？我尝试后好像还是不收敛

**Comment by Xiao9905** [comment]
Hi，
完整版的P-tuning v2代码已经发布在仓库了。根据一些读者的邮件反馈，他们能够使用自己实现的P-tuning  v2复现RTE上的结果。我猜测无法复现的原因，可能还是在代码实现和超参数选择上。
