### ISSUE TITLE
能否先提供一个不完善的版本？

### ISSUE THREAD

**Issue by web199195** [THUDM/P-tuning-v2#7]
您好，我是北科大的学生，在前人的基础上，有个对比学习结合Prompt的思路，想验证一下。看了蛮多论文，您这种方法较为优雅，想尝试一下。但苦于没有代码，没有特别看懂论文。能先提供一个不成熟，不完善的版本吗？拼手速的年代，您一定能理解此刻的心情。  邮箱：601906695@qq.com

**Comment by Xiao9905** [comment]
The codes have been released.
